### PR TITLE
Add repl.it

### PR DESCRIPTION
**Pull request by sixhobbits**
Still a work-in-progress so feel free to close if it doesn't meet "awesome" standards yet :)

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@sixhobbits Hey, looking forward to seeing what more you add. We can keep it open, no worries. Do add some clarification over why the websites you are adding could be great additions to the repository.

**Comment by sixhobbits** [comment]
This is a series of 12 Python projects that both show how to use repl.it (an online IDE) and also teach some coding concepts by example.

I don't think anything big will change in the next days/weeks, so if you don't think it belongs I'd rather close and maybe in 3-6 months time it will have evolved a bit more.

**Review by vipulgupta2048 — APPROVED** [review]
@sixhobbits Not at all, I was thinking you meant you are adding more examples. If this is it, I am okay with merging it

**Comment by sixhobbits** [comment]
great, sorry for the confusion then! I mean I'm still actively working on the docs themselves

**Pull request merged**
